spring: 
 profiles: 
  active:
  - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lhx.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicecloud
    username: root
    password: mysql123
  devtools:
    restart:
      enabled: true


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept-8001 #修改eureka页面 status
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: springcloud-microservice
  create.by: lhx
  build.artifactId: $project.artifactId$
  build.version: $project.version$
